<a href="https://colab.research.google.com/github/nahin333/DL-practice-codes/blob/main/simple_word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding 

In [5]:
reviews = ['nice food',
           'amazing restaurant',
           'too good',
           'just loved it!',
           'will go again',
           'horrible food',
           'never go there',
           'poor service',
           'poor quality',
           'needs improvement']

In [6]:
sentiment = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [8]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[4, 18],
 [15, 7],
 [10, 1],
 [23, 18, 11],
 [17, 1, 27],
 [14, 18],
 [12, 1, 4],
 [18, 20],
 [18, 6],
 [17, 25]]

In [9]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[ 4, 18,  0],
       [15,  7,  0],
       [10,  1,  0],
       [23, 18, 11],
       [17,  1, 27],
       [14, 18,  0],
       [12,  1,  4],
       [18, 20,  0],
       [18,  6,  0],
       [17, 25,  0]], dtype=int32)

In [15]:
embeded_vactor_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vactor_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [16]:
X = padded_reviews
y = sentiment

In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.fit(X, y, epochs=50, verbose=0)

In [23]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 21ms/step - loss: 0.6343 - accuracy: 0.9000


0.8999999761581421

In [25]:
weight = model.get_layer('embedding').get_weights()[0]
len(weight)

30

In [26]:
weight[4]

array([-0.01129622,  0.05842848,  0.08260703,  0.04328085], dtype=float32)

In [27]:
weight[15]

array([-0.0875759 , -0.09464923,  0.081641  , -0.00180174], dtype=float32)